import { defineField, defineType } from 'sanity'

export const bookType = defineType({
  name: 'book',
  title: 'Book',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'isbn',
      title: 'ISBN',
      description: 'Used to auto-fetch the cover image from Open Library.',
      type: 'string',
    }),
    defineField({
      name: 'amazonUrl',
      title: 'Amazon URL',
      description: 'Direct link to the book listing on Amazon.',
      type: 'url',
    }),
    defineField({
      name: 'trailerUrl',
      title: 'Book Trailer (YouTube)',
      description: 'Optional YouTube link, e.g. https://www.youtube.com/watch?v=xxxxx',
      type: 'url',
    }),
    defineField({
      name: 'genre',
      title: 'Primary Genre',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'genres',
      title: 'All Genres',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          'Literary Fiction',
          'Historical Fiction',
          'Romance',
          'Thriller',
          'Sci-Fi',
          'Fantasy',
          'Mystery',
          'Horror',
          'Memoir',
          'Non-Fiction',
          'Business',
          'Self-Help',
          'Poetry',
          'Adventure',
          'Contemporary',
          'Cultural',
          'Writing',
          'Historical',
        ],
      },
    }),
    defineField({
      name: 'price',
      title: 'Paperback Price',
      description: 'e.g. 14.99 (no $ sign). Used as the base / default price.',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).precision(2),
    }),
    defineField({
      name: 'hardcoverPrice',
      title: 'Hardcover Price',
      description: 'e.g. 24.99 — leave blank if not available.',
      type: 'number',
      validation: (Rule) => Rule.min(0).precision(2),
    }),
    defineField({
      name: 'ebookPrice',
      title: 'eBook Price',
      description: 'e.g. 9.99 — leave blank if not available.',
      type: 'number',
      validation: (Rule) => Rule.min(0).precision(2),
    }),
    defineField({
      name: 'audiobookPrice',
      title: 'Audiobook Price',
      description: 'e.g. 19.99 — leave blank if not available.',
      type: 'number',
      validation: (Rule) => Rule.min(0).precision(2),
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      type: 'number',
      validation: (Rule) => Rule.min(0).max(5).precision(1),
    }),
    defineField({
      name: 'reviewCount',
      title: 'Review Count',
      type: 'number',
      validation: (Rule) => Rule.min(0).integer(),
    }),
    defineField({
      name: 'isNewRelease',
      title: 'New Release',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      description: 'One-liner shown on cards and in the quick preview.',
      type: 'string',
      validation: (Rule) => Rule.required().max(160),
    }),
    defineField({
      name: 'description',
      title: 'Full Description',
      type: 'text',
      rows: 5,
    }),
    defineField({
      name: 'publishedDate',
      title: 'Published Date',
      type: 'date',
    }),
    defineField({
      name: 'pageCount',
      title: 'Page Count',
      type: 'number',
      validation: (Rule) => Rule.min(1).integer(),
    }),
    defineField({
      name: 'formats',
      title: 'Available Formats',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Paperback',  value: 'Paperback'  },
          { title: 'Hardcover',  value: 'Hardcover'  },
          { title: 'eBook',      value: 'eBook'      },
          { title: 'Audiobook',  value: 'Audiobook'  },
        ],
      },
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'author',
    },
  },
})
